ci:
  skip: [flake8]

exclude: .+\.txt$|.+\.ascii$

repos:
  # Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.0.0"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        minimum_pre_commit_version: 2.9.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  # Linters

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.285
    hooks:
      - id: ruff

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        types: [file]
        types_or: [python, pyi, markdown, rst, jupyter]
        args: ["--ignore-words-list=doas"]
