exclude: .+\.txt$|.+\.ascii$

repos:
  # Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.21.2"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: "v3.6.2"
    hooks:
      - id: prettier

  # Notebook tools
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        args:
          - "--drop-empty-cells"
          - "--extra-keys"
          - "metadata.vscode metadata.papermill metadata.language_info.version cell.metadata.papermill"

  # Linters

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.15
    hooks:
      - id: ruff
        name: "ruff sort imports"
        args:
          - "--fix"
          - "--select=I"
        alias: isort
      - id: ruff-format
      # Commands above are both formatters and not linters
      # See also: https://github.com/astral-sh/ruff/discussions/7310#discussioncomment-7102010
      - id: ruff
        name: "ruff lint"

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        types: [file]
        types_or: [python, pyi, markdown, rst, jupyter]
        args: ["--ignore-words-list=doas"]
