# Exclude a variety of commonly ignored directories.

# Same as Black.
line-length = 99

# Assume Python 3.10.
target-version = "py310"

[lint]
select = ["ALL"]

ignore = [
  "T201",
  # Covered by formatter
  "ISC001",
  "COM812",
]
external = ["DOC"]

[lint.per-file-ignores]
"scripts/run_notebooks.py" = ["T201", "D103", "INP001", "D100"]

[lint.pydocstyle]
convention = "numpy"
